#!/bin/bash

echo "🎨 Dark-Red Theme Demonstration"
echo "================================"
echo ""
echo "This dotfiles repository now includes a new Dark-Red theme that provides:"
echo ""
echo "✨ Features:"
echo "  • Much darker base colors (near-black backgrounds)"
echo "  • Bright red (#ff4444) accent color throughout"
echo "  • High contrast for better visibility"
echo "  • Consistent styling across all desktop components"
echo ""
echo "🖥️  Components themed:"
echo "  • Hyprland (window manager)"
echo "  • Waybar (status bar)" 
echo "  • Wofi (application launcher)"
echo "  • Kitty (terminal)"
echo "  • SwayNC (notifications)"
echo "  • Spicetify (Spotify client)"
echo ""
echo "🎯 Color Scheme:"
echo "  • Base: #0d0d0d (very dark)"
echo "  • Text: #e6e9ef (bright white)"
echo "  • Accent: #ff4444 (bright red)"
echo "  • Surface: #1e1e2e → #45475a (dark grays)"
echo ""
echo "🚀 Usage:"
echo "  • Switch to dark-red: ./switch-to-dark-red.sh"
echo "  • Switch back to mocha: ./switch-to-mocha.sh"
echo "  • See DARK-RED-THEME.md for detailed instructions"
echo ""
echo "The theme is currently active in this repository!"
echo "All configuration files have been updated to use the dark-red theme."